##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  wutong配置  ###################
wutong: 
  swagger-open: false #是否开启swagger (true/false)
  kaptcha-open: true #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  bidFileUploadPath: F:\\devtools\\other-eclipse\\oxygen\\eclipse3-workspaces\\wutong-back-root\\wutong-back-web\\src\\main\\webapp\\upload\\bidpublicity\\
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  oss:
    prefix: http://wut-publicity.oss-cn-beijing.aliyuncs.com
  ueditor:
    config:
      path: F:\devtools\other-eclipse\oxygen\eclipse3-workspaces\wutong-back-root\wutong-back-web\src\main\webapp\static\ueditor\jsp
      rootPath: F:\devtools\other-eclipse\oxygen\eclipse3-workspaces\wutong-back-root\wutong-back-web\src\main\webapp
  upload:
    tmp-dir:
      filePath:

###################  项目启动端口  ###################
server:
  port: 8080


###################  MyBatis 配置  ###################
mybatis:
    type-aliases-package: com.wutong.backmanage.pojo
    mapper-locations: classpath:com/wutong/backmanage/**/*.xml


###################  MyBatis 分页插件配置  ###################
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false


###################  spring配置  ###################
spring:
  redis:
    host: 192.168.3.189
    port: 6379
    password:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  dubbo: 
    scan: com.wutong
    registry:
      address: zookeeper://127.0.0.1:2181
    application:
      name: wutong-payment
    module:
      default: false
  session:
    store-type: redis
  resources:
    static-locations: classpath:/upload/,classpath:/static/

---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/wutong_manage?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      filters: log4j,wall,mergeStat

#多数据源
biz:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wutong_manage?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: wutong.log

---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/wutong_manage?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      filters: log4j,wall,mergeStat

logging:
  level.root: warn
  path: logs/
  file: wutong.log

